---
# These variables are user defined and can be changed as needed.

# The default location of the network interface configuration files.
default_ifcfg_dir: /etc/sysconfig/network-scripts

# The following interface variables are being used as a dictionary by the 'bond'
# role 'ifcfg-dev.j2' template. The common_cfg variables are common across the
# bond interfaces.
common_cfg:
  bootproto: none
  onboot: "yes"
  peerdns: "no"
  nozeroconf: "yes"

# The bond configs below are specific to the 'bond' role and can be modified as
# needed.
bond_cfg:
  type: bond
  userctl: "no"
  bonding_master: "yes"
  bonding_opts: "\"miimon=100 mode=802.3ad\""

bond_team_cfg:
  type: Ethernet
  slave: "yes"
