---
# This role will create the network bond on the specified hosts with the defined
# parameters found in both the '/inventory/host_vars/host_name.yml' and '/roles/iface/defaults/main.yml'
# files.

- name: Deploy the network vlan interface config file
  template:
    src: ifcfg-dev.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.value['bond'] }}.{{ item.value['vlan'] }}
  with_dict: "{{ vlan_interface }}"
  register: iface_ifcfg

- name: Restart the network bond interfaces with new config
  shell: ifdown {{ item.value['bond'] }}.{{ item.value['vlan'] }} && ifup {{ item.value['bond'] }}.{{ item.value['vlan'] }}
  ignore_errors: yes
  with_dict: "{{ vlan_interface }}"
  when: iface_ifcfg.changed
