---
# This role will create the network bond on the specified hosts with the defined
# parameters found in the '/inventory/host_vars/host.yml' and '/roles/bonds/defaults/main.yml'
# files.

- name: Deploy the network bond interface config file
  template:
    src: ifcfg-dev.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.interface }}
  with_items: "{{ bond_device }}"
  register: bond_ifcfg

- name: Restart the network bond interfaces with new config
  shell: ifdown {{ item.interface }} && ifup {{ item.interface }}
  ignore_errors: yes
  with_items: "{{ bond_device }}"
  when: bond_ifcfg.changed
